spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flyway?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
