version: "3.3"

services:
  mysql-database:
    container_name: mysql-database
    platform: linux/amd64
    image: mysql:5.7
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "13306:3306"

    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d