spring:
  application:
    name: grpc-springboot-consumer

server:
  port: 8081

grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
