apiVersion: v1
kind: Pod
metadata:
  name: projected-volume-example

spec:
  containers:
    - name: projected-volume-example-app
      image: pushyzheng/projected-volume-example:latest
      volumeMounts:
        - name: mysql-cred
          mountPath: "/projected-volume"
          readOnly: true

  volumes:
    - name: mysql-cred
      projected:
        sources:
          - secret:
              name: user
          - secret:
              name: password